import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Bell, Check, ChevronDown, Clock3, Heart, ImagePlus, MapPin, Menu, Package, Plus, Search, ShieldCheck, SlidersHorizontal, UserRound, X, Zap } from 'lucide-react'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import './App.css'

const categories = ['All items', 'Study', 'Tech', 'Sports', 'Lifestyle']
const previewItems = [
  { id: 'preview-1', title: 'TI-84 Plus Calculator', category: 'Study', condition: 'Like new', location: 'North Campus', owner: 'Ananya S.', image: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=900&q=80' },
  { id: 'preview-2', title: 'MacBook USB-C Hub', category: 'Tech', condition: 'Good', location: 'Library block', owner: 'Rohan M.', image: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80' },
  { id: 'preview-3', title: 'Wilson Basketball', category: 'Sports', condition: 'Great', location: 'Sports complex', owner: 'Dev P.', image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=900&q=80' },
]

function App() {
  const [session, setSession] = useState(null)
  const [profile, setProfile] = useState(null)
  const [items, setItems] = useState([])
  const [requests, setRequests] = useState([])
  const [query, setQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState('All items')
  const [activeTab, setActiveTab] = useState('discover')
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState('login')
  const [selectedItem, setSelectedItem] = useState(null)
  const [listOpen, setListOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [loading, setLoading] = useState(true)
  const [mobileNav, setMobileNav] = useState(false)

  useEffect(() => {
    if (!isSupabaseConfigured) { setLoading(false); return undefined }
    supabase.auth.getSession().then(({ data }) => setSession(data.session))
    const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession))
    return () => listener.subscription.unsubscribe()
  }, [])

  useEffect(() => {
    if (!session) { setProfile(null); setItems([]); setRequests([]); return undefined }
    loadData()
    const channel = supabase.channel('borrowbox-live').on('postgres_changes', { event: '*', schema: 'public', table: 'items' }, loadData).on('postgres_changes', { event: '*', schema: 'public', table: 'borrow_requests' }, loadData).subscribe()
    return () => { supabase.removeChannel(channel) }
  }, [session])

  async function loadData() {
    setLoading(true)
    const [{ data: profileData }, { data: itemData }, { data: requestData }] = await Promise.all([
      supabase.from('profiles').select('*').eq('id', session.user.id).single(),
      supabase.from('items').select('*, profiles:owner_id(full_name)').order('created_at', { ascending: false }),
      supabase.from('borrow_requests').select('*, items(title, image_url), borrower:borrower_id(full_name), owner:owner_id(full_name)').order('created_at', { ascending: false }),
    ])
    setProfile(profileData); setItems(itemData || []); setRequests(requestData || []); setLoading(false)
  }

  const visibleItems = useMemo(() => (isSupabaseConfigured && session ? items : previewItems).filter((item) => {
    return (activeCategory === 'All items' || item.category === activeCategory) && `${item.title} ${item.category} ${item.location}`.toLowerCase().includes(query.toLowerCase())
  }), [activeCategory, items, query, session])
  const pending = requests.filter((request) => (request.borrower_id === session?.user?.id || request.owner_id === session?.user?.id) && request.status === 'pending').length
  function showToast(message) { setToast(message); window.setTimeout(() => setToast(''), 3200) }
  async function signOut() { await supabase?.auth.signOut(); showToast('You have been signed out') }

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#top" onClick={() => setActiveTab('discover')}><span className="brand-mark"><Package size={18} /></span><span>borrow<span>box</span></span></a><nav className={mobileNav ? 'nav-links open' : 'nav-links'}><button className={activeTab === 'discover' ? 'nav-link active' : 'nav-link'} onClick={() => { setActiveTab('discover'); setMobileNav(false) }}>Discover</button><button className={activeTab === 'activity' ? 'nav-link active' : 'nav-link'} onClick={() => { setActiveTab('activity'); setMobileNav(false) }}>My activity <span className="nav-count">{pending}</span></button><button className={activeTab === 'listed' ? 'nav-link active' : 'nav-link'} onClick={() => { setActiveTab('listed'); setMobileNav(false) }}>My listings</button></nav><div className="header-actions"><button className="icon-button notification-button" aria-label="Notifications" onClick={() => setActiveTab('activity')}><Bell size={19} />{pending > 0 && <i />}</button>{session ? <><button className="profile-pill" onClick={() => showToast('Profile settings are coming next')}><span className="avatar">{(profile?.full_name || session.user.email || 'Y')[0].toUpperCase()}</span><span className="profile-name">{profile?.full_name?.split(' ')[0] || 'Student'}</span><ChevronDown size={15} /></button><button className="text-button signout" onClick={signOut}>Sign out</button></> : <button className="button button-dark header-login" onClick={() => setAuthOpen(true)}>Log in</button>}<button className="mobile-menu" aria-label="Open menu" onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X size={21} /> : <Menu size={21} />}</button></div></header>
    <main id="top">{!isSupabaseConfigured && <div className="setup-banner"><ShieldCheck size={16} /><span><strong>Preview mode.</strong> Add your Supabase keys to connect BorrowBox to a real database.</span><a href="https://supabase.com" target="_blank" rel="noreferrer">Set up Supabase <ArrowRight size={14} /></a></div>}{activeTab === 'discover' && <DiscoverView items={visibleItems} query={query} setQuery={setQuery} activeCategory={activeCategory} setActiveCategory={setActiveCategory} onSelect={setSelectedItem} onList={() => session ? setListOpen(true) : setAuthOpen(true)} loading={loading} />}{activeTab === 'activity' && <ActivityView requests={requests} session={session} onLogin={() => setAuthOpen(true)} onUpdate={loadData} showToast={showToast} />}{activeTab === 'listed' && <ListingsView items={items.filter((item) => item.owner_id === session?.user?.id)} onList={() => session ? setListOpen(true) : setAuthOpen(true)} onSelect={setSelectedItem} onDelete={async (id) => { await supabase.from('items').delete().eq('id', id); loadData(); showToast('Listing deleted') }} onLogin={() => setAuthOpen(true)} />}</main>
    <footer><div className="footer-brand"><span className="brand-mark"><Package size={15} /></span><strong>borrowbox</strong></div><span>Made for campus communities</span><span className="footer-right">© 2025 BorrowBox</span></footer>
    {toast && <div className="toast"><Check size={16} />{toast}</div>}{authOpen && <AuthModal mode={authMode} setMode={setAuthMode} onClose={() => setAuthOpen(false)} showToast={showToast} />}{listOpen && <ListModal session={session} onClose={() => setListOpen(false)} onSaved={() => { setListOpen(false); loadData(); showToast('Your item is now listed') }} />}{selectedItem && <ItemModal item={selectedItem} session={session} onClose={() => setSelectedItem(null)} showToast={showToast} onRequested={() => { setSelectedItem(null); showToast('Request sent to the owner'); loadData() }} />}
  </div>
}

function DiscoverView({ items, query, setQuery, activeCategory, setActiveCategory, onSelect, onList, loading }) { return <><section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> The campus sharing network</div><h1>Borrow more.<br /><em>Own less.</em></h1><p>Find what you need from people around campus.<br />Lend what you have, earn trust, keep it moving.</p><div className="hero-buttons"><button className="button button-accent" onClick={() => document.getElementById('browse').scrollIntoView({ behavior: 'smooth' })}>Browse items <ArrowRight size={17} /></button><button className="text-button" onClick={onList}><Plus size={17} /> List something</button></div><div className="hero-note"><div className="avatar-stack"><span>J</span><span>M</span><span>K</span><span>+</span></div><span>Join <strong>1,200+</strong> students already sharing</span></div></div><div className="hero-art"><div className="art-paper paper-back" /><div className="art-paper paper-front"><div className="paper-label">BORROW<br /><b>BOX</b></div><div className="paper-lines" /><div className="paper-sticker">↗</div></div><div className="art-tape" /><div className="art-caption">Good things<br /><strong>go around.</strong></div></div></section><section className="trust-strip"><span><Zap size={16} /> Quick to find</span><span><ShieldCheck size={16} /> Community trusted</span><span><Heart size={16} /> Better together</span><span className="trust-spacer" /><small>Built by students, for students</small></section><section className="browse-section" id="browse"><div className="section-heading"><div><div className="eyebrow muted">EXPLORE THE COMMUNITY</div><h2>Find your next <em>useful thing.</em></h2></div><span className="result-count">{items.length} items nearby</span></div><div className="toolbar"><div className="search-box"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search calculators, cameras, textbooks..." /></div><div className="category-scroll">{categories.map((category) => <button key={category} className={activeCategory === category ? 'category active' : 'category'} onClick={() => setActiveCategory(category)}>{category}</button>)}</div><button className="filter-button"><SlidersHorizontal size={16} /> Filters</button></div>{loading ? <div className="state-box"><div className="loader" />Loading your campus...</div> : items.length ? <div className="item-grid">{items.map((item) => <ItemCard key={item.id} item={item} onSelect={onSelect} />)}</div> : <div className="state-box"><Package size={30} /><strong>No items found</strong><span>Try another search or category.</span></div>}<div className="browse-bottom"><span>Showing items from your campus community</span><button className="text-button">View all items <ArrowRight size={16} /></button></div></section></> }

function ItemCard({ item, onSelect }) { const image = item.image_url || item.image; return <article className="item-card" onClick={() => onSelect(item)}><div className="item-image">{image ? <img src={image} alt={item.title} /> : <div className="image-placeholder"><Package size={30} /></div>}<button className="save-button" aria-label="Save item" onClick={(event) => event.stopPropagation()}><Heart size={17} /></button><span className="available-badge"><span /> Available</span></div><div className="item-content"><div className="item-meta"><span>{item.category}</span><span>•</span><span>{item.condition}</span></div><h3>{item.title}</h3><div className="item-footer"><span className="location"><MapPin size={14} />{item.location || 'Campus'}</span><span className="owner">{item.profiles?.full_name || item.owner || 'Student'}</span></div></div></article> }

function ActivityView({ requests, session, onLogin, onUpdate, showToast }) { if (!session) return <EmptyAuth title="Your activity, all in one place." copy="Log in to track your borrowing requests, returns, and lending history." onLogin={onLogin} />; return <section className="page-section"><div className="page-heading"><div><div className="eyebrow muted">YOUR BORROWBOX</div><h1>My <em>activity.</em></h1><p>Keep track of the things moving through your campus community.</p></div><div className="activity-stats"><span><strong>{requests.filter((request) => request.borrower_id === session.user.id).length}</strong> borrowed</span><span><strong>{requests.filter((request) => request.owner_id === session.user.id).length}</strong> lending</span></div></div><div className="activity-list">{requests.length ? requests.map((request) => <RequestRow key={request.id} request={request} isOwner={request.owner_id === session.user.id} onUpdate={onUpdate} showToast={showToast} />) : <div className="state-box"><Clock3 size={30} /><strong>No activity yet</strong><span>Browse the community to get started.</span></div>}</div></section> }
function RequestRow({ request, isOwner, onUpdate, showToast }) { const statusLabel = request.status === 'approved' ? 'Approved' : request.status === 'rejected' ? 'Declined' : request.status === 'returned' ? 'Returned' : 'Awaiting response'; async function updateStatus(status) { await supabase.from('borrow_requests').update({ status }).eq('id', request.id); onUpdate(); showToast(status === 'approved' ? 'Request approved' : 'Request updated') } return <div className="request-row"><div className="request-icon"><Package size={20} /></div><div className="request-info"><strong>{request.items?.title || 'Item request'}</strong><span>{isOwner ? `From ${request.borrower?.full_name || 'a student'}` : `Owner: ${request.owner?.full_name || 'a student'}`} · {new Date(request.created_at).toLocaleDateString()}</span></div><span className={`status status-${request.status}`}>{statusLabel}</span>{isOwner && request.status === 'pending' && <div className="request-actions"><button className="small-button approve" onClick={() => updateStatus('approved')}>Accept</button><button className="small-button" onClick={() => updateStatus('rejected')}>Decline</button></div>}</div> }
function ListingsView({ items, onList, onSelect, onDelete, onLogin }) { if (!isSupabaseConfigured) return <EmptyAuth title="Your listings live here." copy="Connect Supabase and log in to share items with your campus community." onLogin={onLogin} />; return <section className="page-section"><div className="page-heading"><div><div className="eyebrow muted">SHARE YOUR STUFF</div><h1>My <em>listings.</em></h1><p>Keep useful things circulating instead of sitting on a shelf.</p></div><button className="button button-accent" onClick={onList}><Plus size={17} /> New listing</button></div>{items.length ? <div className="listing-list">{items.map((item) => <div className="listing-row" key={item.id} onClick={() => onSelect(item)}><div className="listing-thumb">{item.image_url ? <img src={item.image_url} alt="" /> : <Package size={22} />}</div><div><strong>{item.title}</strong><span>{item.category} · {item.location}</span></div><span className="status status-approved">Available</span><button className="delete-button" onClick={(event) => { event.stopPropagation(); onDelete(item.id) }}><X size={17} /></button></div>)}</div> : <div className="state-box"><ImagePlus size={30} /><strong>No listings yet</strong><span>List your first item and help someone out.</span><button className="button button-dark" onClick={onList}>List an item</button></div>}</section> }
function EmptyAuth({ title, copy, onLogin }) { return <section className="empty-auth"><div className="empty-icon"><UserRound size={28} /></div><h1>{title}</h1><p>{copy}</p><button className="button button-dark" onClick={onLogin}>Log in to continue <ArrowRight size={16} /></button></section> }

function AuthModal({ mode, setMode, onClose, showToast }) { const [loading, setLoading] = useState(false); async function submit(event) { event.preventDefault(); setLoading(true); const form = new FormData(event.currentTarget); const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email: form.get('email'), password: form.get('password') }) : await supabase.auth.signUp({ email: form.get('email'), password: form.get('password'), options: { data: { full_name: form.get('name') } } }); setLoading(false); if (result.error) showToast(result.error.message); else { onClose(); showToast(mode === 'login' ? 'Welcome back' : 'Check your email to confirm your account') } } return <div className="modal-backdrop" onMouseDown={onClose}><div className="auth-modal" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={19} /></button><div className="modal-mark"><Package size={22} /></div><div className="eyebrow muted">WELCOME TO BORROWBOX</div><h2>{mode === 'login' ? 'Good to see you.' : 'Join the circle.'}</h2><p>{mode === 'login' ? 'Log in to borrow, lend, and keep things moving.' : 'Create your student account and start sharing.'}</p><form onSubmit={submit}>{mode === 'signup' && <label>Full name<input name="name" required placeholder="Your name" /></label>}<label>College email<input name="email" type="email" required placeholder="you@college.edu" /></label><label>Password<input name="password" type="password" required minLength="6" placeholder="At least 6 characters" /></label><button className="button button-accent wide" disabled={loading}>{loading ? 'Working...' : mode === 'login' ? 'Log in' : 'Create account'} <ArrowRight size={16} /></button></form><div className="switch-auth">{mode === 'login' ? 'New here?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create an account' : 'Log in'}</button></div></div></div> }
function ListModal({ session, onClose, onSaved }) { const [saving, setSaving] = useState(false); async function submit(event) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); let imageUrl = null; const image = form.get('image'); if (image?.size) { const path = `${session.user.id}/${Date.now()}-${image.name}`; const upload = await supabase.storage.from('item-images').upload(path, image); if (!upload.error) imageUrl = supabase.storage.from('item-images').getPublicUrl(path).data.publicUrl } const { error } = await supabase.from('items').insert({ owner_id: session.user.id, title: form.get('title'), description: form.get('description'), category: form.get('category'), condition: form.get('condition'), location: form.get('location'), image_url: imageUrl }); setSaving(false); if (!error) onSaved() } return <div className="modal-backdrop" onMouseDown={onClose}><div className="form-modal" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={19} /></button><div className="eyebrow muted">PUT IT TO GOOD USE</div><h2>List an item</h2><p>Give something useful a second life on campus.</p><form onSubmit={submit}><label>Item name<input name="title" required placeholder="e.g. Graphing calculator" /></label><div className="form-row"><label>Category<select name="category" defaultValue="Study"><option>Study</option><option>Tech</option><option>Sports</option><option>Lifestyle</option></select></label><label>Condition<select name="condition" defaultValue="Good"><option>Like new</option><option>Good</option><option>Used</option></select></label></div><label>Pickup location<input name="location" required placeholder="e.g. Main library" /></label><label>Description<textarea name="description" rows="3" placeholder="Tell borrowers what they should know..." /></label><label className="file-label"><ImagePlus size={18} /> Add a photo<input name="image" type="file" accept="image/*" /></label><button className="button button-accent wide" disabled={saving}>{saving ? 'Publishing...' : 'Publish listing'} <ArrowRight size={16} /></button></form></div></div> }
function ItemModal({ item, session, onClose, showToast, onRequested }) { const [sending, setSending] = useState(false); async function requestItem() { if (!session) { showToast('Log in to request an item'); return } setSending(true); const { error } = await supabase.from('borrow_requests').insert({ item_id: item.id, borrower_id: session.user.id, owner_id: item.owner_id }); setSending(false); if (error) showToast(error.message); else onRequested() } return <div className="modal-backdrop" onMouseDown={onClose}><div className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={19} /></button><div className="detail-image">{(item.image_url || item.image) ? <img src={item.image_url || item.image} alt={item.title} /> : <Package size={45} />}</div><div className="detail-body"><div className="item-meta"><span>{item.category}</span><span>•</span><span>{item.condition}</span></div><h2>{item.title}</h2><p>{item.description || 'A useful item shared by someone in your campus community.'}</p><div className="detail-owner"><div className="avatar">{(item.profiles?.full_name || item.owner || 'S')[0]}</div><div><strong>{item.profiles?.full_name || item.owner || 'Campus student'}</strong><span><MapPin size={13} /> {item.location || 'Campus pickup'}</span></div></div><button className="button button-accent wide" onClick={requestItem} disabled={sending}>{sending ? 'Sending request...' : 'Request to borrow'} <ArrowRight size={16} /></button></div></div></div> }
export default App
